const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";

export type PlannerRecommendationType = "feature" | "analysis" | "feature_and_analysis" | "configuration";
export type PlannerRecommendationStatus = "existing" | "create_new" | "needs_clarification";
export type PmDecisionValue = "accepted" | "rejected" | "pending";

// Flat schema -- see planner.py's system prompt. The Planner only states
// WHAT is required (name/description/required_fields), never a formula or
// output-column name; those are derived downstream (feature_repository.py /
// analysis_repository.py) and the actual computation plan is pre-generated
// separately by the Feature/Analysis Agent's Think step (generated_*_formula
// below).
export interface PlannerRecommendation {
  type: PlannerRecommendationType;
  status: PlannerRecommendationStatus;
  name: string;
  description: string;
  reason: string;
  required_fields: string[];
  missing_fields: string[];
  clarifications_required: string[];
  // Pre-generated by the Feature/Analysis Agent's Think step at suggest
  // time, before the PM sees this recommendation. Null if that call failed
  // (the agent will think one up itself later, at compute time) or if this
  // recommendation's type doesn't need that plan.
  generated_feature_formula?: string | null;
  generated_analysis_formula?: string | null;
  // One-line formula (features) and spec (analyses) from the same Think
  // step, shown above the numbered plan.
  feature_formula_expression?: string | null;
  feature_columns_used?: string[];
  feature_output_dtype?: string | null;
  analysis_logic?: string | null;
  analysis_group_by?: string[];
  analysis_metrics?: string[];
  pm_decision?: PmDecisionValue;
  pm_notes?: string;
}

export interface PlannerSuggestResponse {
  recommendations: PlannerRecommendation[];
}

export interface PmDecision {
  recommendation_index: number;
  pm_decision: PmDecisionValue;
  pm_notes: string;
}

export interface SaveDecisionsResponse {
  session_id: string;
  saved: boolean;
}

export async function fetchSuggestions(
  sessionId: string,
  additionalContext = ""
): Promise<PlannerSuggestResponse> {
  const res = await fetch(`${API_BASE_URL}/api/planner/suggest`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ session_id: sessionId, additional_context: additionalContext }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Planner suggest failed: ${res.status} ${text}`);
  }
  return res.json();
}

export async function saveDecisions(
  sessionId: string,
  decisions: PmDecision[]
): Promise<SaveDecisionsResponse> {
  const res = await fetch(`${API_BASE_URL}/api/planner/save`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ session_id: sessionId, decisions }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Planner save failed: ${res.status} ${text}`);
  }
  return res.json();
}
