"""Per-session analysis repository: the single place every candidate
analysis lands, regardless of which of the five sources proposed it --

  predefined -- parsed from the uploaded Analysis Profile file
  planner    -- Planner Agent recommendations the PM approved
  custom     -- typed directly into the Analysis page by the PM
  ai_suggested -- proposed by the AI analysis-suggestion agent
  drilldown  -- created when a PM clicks a suggested follow-up on an
                already-computed analysis (see analysis_agent.suggest_drilldowns)

`predefined` and `planner` are derived, not stored -- they always reflect
whatever is currently in the global Analysis Profile store / that session's
planner_output.json, so re-uploading a profile or re-approving planner
recommendations is picked up automatically. `custom`, `ai_suggested`, and
`drilldown` are the only entries actually persisted to
analysis_repository.json (their accept/reject state and PM-authored/
PM-triggered content can't be re-derived from anywhere else). Every read
rebuilds the full merged view.
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from app.config import DATA_DIR
from app.services.analysis import analysis_definitions_store as defs_store

_SESSIONS_DIR = DATA_DIR / "sessions"

_PERSISTED_SOURCES = {"custom", "ai_suggested", "drilldown"}


def _session_dir(session_id: str) -> Path:
    d = _SESSIONS_DIR / session_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def _repo_path(session_id: str) -> Path:
    return _session_dir(session_id) / "analysis_repository.json"


def _planner_output_path(session_id: str) -> Path:
    return _session_dir(session_id) / "planner_output.json"


def _predefined_entries() -> list[dict]:
    if defs_store.store.definitions is None:
        return []
    entries = []
    for spec in defs_store.store.definitions:
        entries.append({
            "id": f"predefined_{spec['id']}",
            "source": "predefined",
            "status": "approved",
            "name": spec["name"],
            "description": spec.get("description", ""),
            "calculation_intent": spec["calculation_intent"],
            "input_columns": spec.get("input_columns", []),
            # A predefined spec may ship its own pre-authored formula (skips
            # Think entirely); otherwise the Analysis Agent thinks one up at
            # compute time, same convention as feature_repository's
            # "ai_generated" predefined type.
            "formula": spec.get("formula"),
            "parent_id": None,
        })
    return entries


def predefined_catalog_lines() -> list[str]:
    """Plain-text lines describing every predefined analysis -- fed into the
    Planner's "existing catalog" context so it recommends things NOT already
    covered by the uploaded Analysis Profile."""
    return [f"[analysis] {e['name']}: {e['description']}" for e in _predefined_entries()]


def _planner_entries(session_id: str) -> list[dict]:
    path = _planner_output_path(session_id)
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    entries = []
    for i, rec in enumerate(data.get("recommendations", [])):
        if rec.get("pm_decision") != "accepted":
            continue
        if rec.get("type") not in ("analysis", "feature_and_analysis"):
            continue
        # The Planner's current schema is flat (name/description/required_fields
        # directly on the recommendation) -- see planner.py's system prompt.
        name = rec.get("name") or f"Planner Analysis {i + 1}"
        entries.append({
            "id": f"planner_analysis_{i}",
            "source": "planner",
            "status": "approved",
            "name": name,
            "description": rec.get("description", ""),
            "calculation_intent": rec.get("description", ""),
            "input_columns": rec.get("required_fields", []),
            # Pre-generated by the Analysis Agent's Think step at Planner
            # suggest time (see planner.py) -- the PM saw and approved THIS
            # plan specifically, so it's carried through verbatim.
            "formula": rec.get("generated_analysis_formula"),
            "parent_id": None,
        })
    return entries


def _load_persisted(session_id: str) -> list[dict]:
    path = _repo_path(session_id)
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    return [e for e in data.get("entries", []) if e.get("source") in _PERSISTED_SOURCES]


def _save(session_id: str, entries: list[dict]) -> None:
    _repo_path(session_id).write_text(
        json.dumps({"session_id": session_id, "entries": entries}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def get_repository(session_id: str) -> list[dict]:
    """The full merged view: freshly-derived predefined + planner entries,
    plus whatever custom/ai_suggested/drilldown entries this session has
    persisted. Also re-saves the merge so the file on disk always reflects
    the latest Analysis Profile / planner decisions. Returns definitions
    only -- run results (table/chart/interpretation) live in-memory on the
    audit session and are merged in by the router."""
    entries = _predefined_entries() + _planner_entries(session_id) + _load_persisted(session_id)
    _save(session_id, entries)
    return entries


def add_custom_entry(
    session_id: str, name: str, description: str, calculation_intent: str, input_columns: list[str], *,
    formula: str | None = None, template: dict | None = None, chart_recommendation: dict | None = None,
    filters: list[dict] | None = None,
) -> dict:
    """Persists a PM-authored analysis. When it was drafted through the
    Analysis Designer it also carries the reviewed computation logic
    (`formula`), an optional deterministic `template`, the chosen chart, and
    its interactive filters -- all already validated by the caller."""
    entry = {
        "id": f"custom_{uuid.uuid4().hex[:8]}",
        "source": "custom",
        "status": "approved",
        "name": name,
        "description": description or calculation_intent,
        "calculation_intent": calculation_intent,
        "input_columns": input_columns,
        "formula": formula,
        "parent_id": None,
        "template": template,
        "chart_recommendation": chart_recommendation,
        "filters": filters or [],
    }
    persisted = _load_persisted(session_id)
    persisted.append(entry)
    entries = _predefined_entries() + _planner_entries(session_id) + persisted
    _save(session_id, entries)
    return entry


def _normalize_name(name: str) -> str:
    """Shared with analysis_suggester so both dedupe names the same way."""
    return " ".join(name.lower().split())


def add_ai_suggested_entries(session_id: str, suggestions: list[dict]) -> list[dict]:
    """Appends new AI-suggested candidates (status=pending), skipping any
    whose name already exists in the repository (case/whitespace-insensitive)
    so re-running suggestions doesn't pile up duplicates."""
    existing = get_repository(session_id)
    existing_names = {_normalize_name(e["name"]) for e in existing}
    persisted = _load_persisted(session_id)

    new_entries = []
    for s in suggestions:
        if _normalize_name(s["name"]) in existing_names:
            continue
        entry = {
            "id": f"ai_{uuid.uuid4().hex[:8]}",
            "source": "ai_suggested",
            "status": "pending",
            "name": s["name"],
            "description": s.get("description", ""),
            "calculation_intent": s["calculation_intent"],
            "input_columns": s.get("input_columns", []),
            "formula": None,
            "parent_id": None,
        }
        persisted.append(entry)
        new_entries.append(entry)
        existing_names.add(_normalize_name(entry["name"]))

    entries = _predefined_entries() + _planner_entries(session_id) + persisted
    _save(session_id, entries)
    return new_entries


def add_drilldown_entry(session_id: str, parent_id: str, drilldown: dict) -> dict:
    """Persists a new entry for a PM-triggered drilldown. Auto-approved --
    the PM's click on "Explore this" IS the approval, there's no separate
    accept step for a drilldown the way there is for an AI suggestion."""
    entry = {
        "id": f"drilldown_{uuid.uuid4().hex[:8]}",
        "source": "drilldown",
        "status": "approved",
        "name": drilldown["name"],
        "description": drilldown.get("description", ""),
        "calculation_intent": drilldown["calculation_intent"],
        "input_columns": [],
        "formula": None,
        "parent_id": parent_id,
    }
    persisted = _load_persisted(session_id)
    persisted.append(entry)
    entries = _predefined_entries() + _planner_entries(session_id) + persisted
    _save(session_id, entries)
    return entry


def set_entry_status(session_id: str, entry_id: str, status: str) -> dict | None:
    persisted = _load_persisted(session_id)
    found = None
    for e in persisted:
        if e["id"] == entry_id:
            e["status"] = status
            found = e
            break
    if found is None:
        return None
    entries = _predefined_entries() + _planner_entries(session_id) + persisted
    _save(session_id, entries)
    return found


def get_entry(session_id: str, entry_id: str) -> dict | None:
    for e in get_repository(session_id):
        if e["id"] == entry_id:
            return e
    return None
